### ISSUE TITLE
智学网成绩总览页面更新界面导致扩展不可用

### ISSUE THREAD

**Issue by aquamarine5** [aquamarine5/ZhixuewangScoreExt#3]
- 因智学网成绩总览页面布局更改，ZhixuewangScoreExtension的功能仅原卷成绩和成就分析页面换九边型战士的图可用

**Comment by awesomehhhhh** [comment]
*20220111 Updated*: 单科成绩暂不可用，原卷成绩和总分成绩分析页面可用

**Comment by aquamarine5** [comment]
*20220226 Updated*: Available
